### ISSUE TITLE
The prompt selects are only available for the first user input; after ChatGPT responds, subsequent inputs won't have this option.

### ISSUE THREAD

**Issue by leonard2z** [m-c-frank/GPTPromptMaster#19]
When using ChatGPT, I noticed that the prompt selects are only available for the first user input. Once ChatGPT responds, subsequent user inputs don't have this option.

![image](https://user-images.githubusercontent.com/37145130/233426685-728469c8-c105-4bce-9c59-ce4222418b1f.png)

![image](https://user-images.githubusercontent.com/37145130/233426784-e7d6af1c-2040-4dcc-acb1-3e5c393b028d.png)

**Comment by leonard2z** [comment]
The issue is that ChatGPT does not retain information effectively, therefore we must remind it of the necessary details with each new prompt we send

**Comment by m-c-frank** [comment]
I am now investigating this issue!

**Comment by m-c-frank** [comment]
No longer required as this project is archived
